
spring:
  application:
    name: Config-Server
  config:
    name: configserver
  profiles:
    active:
    - dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
#          searchPaths: '{application}'
          default-label: main
          
server:
  port: 8888
  
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true