spring:
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
#          searchPaths: '{application}'
          default-label: main